- name: loops in ansible
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages using loop
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name:"mysql", state:"present" }
    - { name:"nginx", state:"present" }